# Generated by Django 3.1.7 on 2021-03-17 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20210316_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='address',
        ),
        migrations.RemoveField(
            model_name='post',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='contact_email',
        ),
    ]
