# Generated by Django 3.1.7 on 2021-03-17 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20210317_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='position',
        ),
        migrations.AddField(
            model_name='post',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='resume',
            field=models.FileField(null=True, upload_to='resume/%Y/%m'),
        ),
        migrations.AddField(
            model_name='post',
            name='vacancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.vacancy'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contact_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser'),
        ),
    ]
