# Generated by Django 3.1.7 on 2021-03-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20210317_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
