# Generated by Django 3.1.7 on 2021-03-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20210317_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
