# Generated by Django 3.1.7 on 2021-03-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20210318_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='resume',
        ),
    ]
