# Generated by Django 3.1.7 on 2021-03-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20210318_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='last_name',
        ),
    ]
