# Generated by Django 3.1.7 on 2021-03-18 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_vacancy_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='slug',
        ),
    ]
