# Generated by Django 3.1.7 on 2021-03-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_remove_vacancy_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/%Y/%m'),
        ),
    ]
