# Generated by Django 3.1.7 on 2021-03-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_auto_20210318_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='resume',
            field=models.FileField(upload_to='resume/%Y/%m'),
        ),
    ]
