# Generated by Django 3.1.7 on 2021-03-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_auto_20210318_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='resume',
            field=models.FileField(null=True, upload_to='resume/%Y/%m'),
        ),
    ]
