# Generated by Django 3.1.7 on 2021-03-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_auto_20210318_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='resume',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
