# Generated by Django 3.1.7 on 2021-03-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='vacancy',
        ),
    ]
