# Generated by Django 3.1.7 on 2021-03-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_remove_language_vacancy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
