# Generated by Django 3.1.7 on 2021-03-20 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_delete_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.vacancy'),
        ),
    ]
